# Docker Compose file for local development services
# Note: This is optional since you're using cloud services
# You can remove this file if all your services are in the cloud

version: '3.8'

# Uncomment the services below if you need local development versions
# services:
#   postgres:
#     image: postgres:15
#     container_name: pdf_rag_postgres_local
#     environment:
#       POSTGRES_DB: pdf_rag
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped

#   redis:
#     image: redis:7-alpine
#     container_name: pdf_rag_redis_local
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     restart: unless-stopped

#   qdrant:
#     image: qdrant/qdrant:latest
#     container_name: pdf_rag_qdrant_local
#     ports:
#       - "6333:6333"
#       - "6334:6334"
#     volumes:
#       - qdrant_data:/qdrant/storage
#     restart: unless-stopped

# volumes:
#   postgres_data:
#   redis_data:
#   qdrant_data:
