version: '3.8'

services:
  pdf-rag-db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports: ["5432:5432"]
    volumes: ["pg_data:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]


  valkey:
    image: valkey/valkey
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli PING"]

  qdrant:
    image: qdrant/qdrant
    ports: ["6333:6333"]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: ["5000:5000"]
    depends_on:
      pdf-rag-db:
        condition: service_healthy
      valkey:
        condition: service_healthy
      qdrant:
        condition: service_started
    environment:
      DATABASE_URL: postgres://root:root@pdf-rag-db:5432/db
      REDIS_URL: redis://valkey:6379
      QDRANT_URL: http://qdrant:6333

  queue:
    build:
      context: ./queues
      dockerfile: Dockerfile
    depends_on:
      pdf-rag-db:
        condition: service_healthy
      valkey:
        condition: service_healthy
    environment:
      REDIS_URL: redis://valkey:6379
      DATABASE_URL: postgres://root:root@pdf-rag-db:5432/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:5000

volumes:
  pg_data:
