version: '3.8'

services:
  pdf-rag-db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports: ["5432:5432"]
    volumes: ["pg_data:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]


  valkey:
    image: valkey/valkey
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli PING"]

  qdrant:
    image: qdrant/qdrant
    ports: ["6333:6333"]


volumes:
  pg_data:
